export const FETCH_ARTIST = "FETCH_ARTIST";
export const FETCH_ARTIST_ERROR = "FETCH_ARTIST_ERROR";

export const CLEAR_SEARCH_HISTORY = "CLEAR_SEARCH_HISTORY";
export const FETCH_SEARCH_HISTORY = "FETCH_SEARCH_HISTORY";
