export const FETCH_ARTIST = "FETCH_ARTIST";
export const FETCH_ARTIST_ERROR = "FETCH_ARTIST_ERROR";

export const FETCH_SEARCH_HISTORY = "FETCH_SEARCH_HISTORY";
export const ADD_TO_SEARCH_HISTORY = "ADD_TO_SEARCH_HISTORY";
export const CLEAR_SEARCH_HISTORY = "CLEAR_SEARCH_HISTORY";

export const FETCH_FAVORITES = "FETCH_FAVORITES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
