version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2

jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

workflows:
  build-and-deploy:
    jobs:
      - build # perform this first
      - heroku/deploy-via-git: # perform second
          requires:
            - build
          filters: # only for the master branch
            branches:
              only: master
